language: python
cache: pip
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script:
  - py.test --cov=icloudpd
  - pylint icloudpd

after_success:
  - coveralls
